services:
  web:
    image: nginx:alpine
    container_name: mi-pagina-web
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
