version: '3.8'  # Versión del esquema de Docker Compose (compatible con Docker 27.x)

services:
  web:
    image: nginx:alpine  # Usa una imagen de NGINX basada en Alpine Linux
    container_name: mi-pagina-web  # Nombre personalizado para el contenedor
    ports:
      - "8080:80"  # Mapea el puerto 80 del contenedor al puerto 8080 de tu PC
    volumes:
      - .:/usr/share/nginx/html  # Monta la carpeta actual en el contenedor
    environment:
      - NGINX_HOST=localhost  # Variable de entorno para NGINX (opcional)
    restart: unless-stopped  # Reinicia el contenedor automáticamente
    networks:
      - web-network  # Conecta el servicio a una red personalizada

networks:
  web-network:  # Define una red personalizada para los servicios
    driver: bridge